export { page1 } from './page1.js'
export { page2 } from './page2.js'
export { page3 } from './page3.js'
export { last } from './last.js'
export { page1extended } from './page1_extended.js'
export { page2extended } from './page2_extended.js'
export { page3extended } from './page3_extended.js'
